"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--))!d=j(mq+ij^$v)!x%%(5o%he^=t=q)*hg+(*+jy*kkxc75m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    # --- Bawaan Django ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Library Pihak Ketiga ---
    'rest_framework',
    'corsheaders',

    # --- Microservices Sistem Jual Beli Laptop ---
    'apps.app_users',
    'apps.app_katalog',
    'apps.app_pesanan',      
    'apps.app_pembayaran',
    'apps.app_notifikasi',
    'apps.app_pengiriman',
    
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <-- Wajib diletakkan di atas CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database Configuration for Microservices Approach
# Pastikan db_utama, db_ms_users, db_ms_katalog, dll sudah dibuat di phpMyAdmin

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_utama',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'users_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_users',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'katalog_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_katalog',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'pesanan_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_pesanan',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'pembayaran_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_pembayaran',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'notifikasi_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_notifikasi',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'pengiriman_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_ms_pengiriman',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
}

# Memberitahu Django untuk menggunakan router kustom
DATABASE_ROUTERS = ['core.routers.MicroserviceRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os 

# Media files (File yang diupload seperti gambar produk)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- KONFIGURASI TAMBAHAN ---

# Mengizinkan React (Frontend) untuk berkomunikasi dengan API Django (Backend)
CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'app_users.CustomUser'

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

JAZZMIN_SETTINGS = {
    "site_title": "Admin UnivStore",
    "site_header": "UnivStore",
    "site_brand": "UnivStore",
    "welcome_sign": "Selamat Datang di Management System",
    "copyright": "Kelompok IAE",
    "search_model": ["app_katalog.Produk"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["app_users", "app_katalog", "app_pesanan"],
    "icons": {
        "app_users.CustomUser": "fas fa-users",
        "app_katalog.Produk": "fas fa-laptop",
        "app_pesanan.Pesanan": "fas fa-shopping-cart",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly", 
}

# --- MIDTRANS CONFIGURATION ---
MIDTRANS_SERVER_KEY = os.getenv('MIDTRANS_SERVER_KEY')
MIDTRANS_CLIENT_KEY = os.getenv('MIDTRANS_CLIENT_KEY')
MIDTRANS_IS_PRODUCTION = os.getenv('MIDTRANS_IS_PRODUCTION', 'False').lower() == 'true'