# Generated by Django 5.0.14 on 2026-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabel_notifikasi',
            },
        ),
    ]
