# Generated by Django 5.0.14 on 2026-04-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembeli_id', models.IntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('diproses', 'Sedang Diproses'), ('dikirim', 'Dalam Pengiriman'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabel_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_id', models.IntegerField()),
                ('jumlah', models.IntegerField(default=1)),
                ('harga_saat_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_pesanan.order')),
            ],
            options={
                'db_table': 'tabel_order_item',
            },
        ),
    ]
