# Generated by Django 5.0.14 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat_pengiriman',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pesanan Dibuat'), ('konfirmasi', 'Menunggu Konfirmasi'), ('diproses', 'Laptop Disiapkan'), ('dikirim', 'Sedang Dikirim'), ('selesai', 'Laptop Diterima'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
