# Generated by Django 5.0.14 on 2026-06-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pesanan', '0002_order_alamat_pengiriman_alter_order_status'),
        ('app_pesanan', '0003_order_alamat_pengiriman_order_kota_order_kurir_and_more'),
    ]

    operations = [
    ]
