# Generated by Django 5.0.14 on 2026-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penjual_id', models.IntegerField(help_text='ID Penjual dari tabel app_users')),
                ('nama_laptop', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.IntegerField(default=0)),
                ('spesifikasi', models.JSONField(blank=True, help_text="Contoh: {'RAM': '16GB', 'CPU': 'Intel i7'}", null=True)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Katalog Laptop',
                'db_table': 'tabel_laptop',
            },
        ),
    ]
