# Generated by Django 5.0.14 on 2026-04-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_katalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='penjual_id',
        ),
    ]
