# Generated by Django 5.0.14 on 2026-04-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_katalog', '0002_remove_laptop_penjual_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='katalog/produk/')),
                ('prosesor', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='app_katalog.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
