# Generated by Django 5.0.14 on 2026-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Pelanggan'), ('admin', 'Admin Toko')], default='buyer', max_length=10),
        ),
    ]
