# Generated by Django 5.0.14 on 2026-06-16 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Pengguna', 'verbose_name_plural': 'Daftar Pengguna'},
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerima', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=20)),
                ('alamat_lengkap', models.TextField()),
                ('kota_kabupaten', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('is_utama', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_alamat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Alamat',
                'ordering': ['-is_utama', '-created_at'],
            },
        ),
    ]
