# Generated by Django 5.0.14 on 2026-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_customuser_options_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
