# Generated by Django 5.0.14 on 2026-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('metode', models.CharField(choices=[('transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('cc', 'Kartu Kredit')], max_length=20)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='pembayaran/')),
                ('is_lunas', models.BooleanField(default=False)),
                ('tanggal_konfirmasi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabel_pembayaran',
            },
        ),
    ]
