# Generated by Django 5.0.14 on 2026-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='metode_pembayaran_midtrans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='midtrans_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='status_transaksi',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='waktu_transaksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='metode',
            field=models.CharField(choices=[('midtrans', 'Midtrans Snap'), ('transfer', 'Transfer Bank Manual'), ('qris', 'QRIS'), ('cc', 'Kartu Kredit')], default='midtrans', max_length=50),
        ),
    ]
